### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by davidmind** [andviane/google-books-android-viewer#5]
Hello @andviane i am a graphics designer, i will like to know if you want me to create a logo for your project. I will be creating the logo for free with your permission.

**Comment by andviane** [comment]
Surely I would accept the logo if good enough quality. Mind that the logo will be available as part of the source code of the app under terms of either GPL v3.0 license or any other license that is compatible with it. I assume that by submitting the logo you agree with this condition, and if you no further specify the license I assume GPL v3.0.

Otherwise, yes, I will set your logo as the logo of the book viewer app, all around PlayStore and and F-Droid, will mention you in the app page at https://github.com/andviane/google-books-android-viewer. While GPL v3.0 allows the reuse of modified and unmodified versions, the logo will otherwise will remain your property on that we will claim no ownership.

Best
Audrius

**Comment by davidmind** [comment]
OK, no problem I will work on the logo as soon as possible. I have just read through GPL v3.0 license it is similar with the one I use **[Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/)**

**Comment by davidmind** [comment]
Hi, @andviane sorry it is coming late. I was a little bit busy last week. After checking your project i make some sketch. While i check online to avoid duplicate here is what i came up with.
**1**
![book listmdpi](https://user-images.githubusercontent.com/37777956/42414518-647db6cc-822e-11e8-8f65-5b2d40abf679.png)

**2**
![booklist-2](https://user-images.githubusercontent.com/37777956/42414463-b9f3b1d4-822d-11e8-89b9-9ee9e5b69d74.png)
I will be making an adaptive icon and also make a pull request , while i submit both png and editable files if you like it. You can also make suggestion, based on color and what you will like to be removed.

**Comment by davidmind** [comment]
@andviane

**Comment by davidmind** [comment]
@andviane are you there?

**Comment by andviane** [comment]
This looks great. Please open the PR. Images are in https://github.com/andviane/google-books-android-viewer/tree/master/app/src/main/res subfolders, for various resolutions (Android picks the needed size automatically). Maybe low resolution versions could have slightly more narrow border around so that books and glass would stay well visible. Both versions look good. I would use the version 2 making the magnifying glass larger, all over the book, to make it well visible. But up to you.

**Comment by davidmind** [comment]
Ok i will increase the size of the magnified glass and also ensure the logo fit perfectly for lower resolution, i will submit a preview of the edited version before making a pull request for version 2.

**Comment by davidmind** [comment]
@andviane here is a preview of the icon after it was edited,
![booklist-1](https://user-images.githubusercontent.com/37777956/42602242-789eb8c4-8560-11e8-9084-4d3c2e690cff.png)


 i have also make an adaptable icon for android 8.0 and above i will submit a link to editable and file png before i make the pull request.

**Comment by andviane** [comment]
Looks now great

**Comment by davidmind** [comment]
@andviane i have made a pull request with the icon above, am glad you like it. This is a **[link](https://drive.google.com/drive/folders/1dJKykfKjvcwIBEZCDwkc2nF-4xtfVp_x?usp=sharing)** to editable and png files, if you need anything else concerning the logo i will make it available as soon as possible.

**Comment by andviane** [comment]
Done, I will rebuild and republish to PlayStore.
